version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: ServerDockerfile
    networks:
      my-network:
        ipv4_address: 172.20.0.2
    ports:
    - "5100:5100"

  server_node_1:
    container_name: server_node_1
    depends_on:
      - server
    build:
      dockerfile: ServerNodeDockerfile
    networks:
      my-network:

  server_node_2:
    container_name: server_node_2
    depends_on:
      - server
    build:
      dockerfile: ServerNodeDockerfile
    networks:
      my-network:

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16